runtime: python39
env: flex

runtime_config:
  python_version: 3

resources:
 cpu: 2
  memory_gb: 2
  disk_size_gb: 10

env_variables:
  APP_LOG_LEVEL: "ERROR"

manual_scaling:
  instances: 1

entrypoint: gunicorn -b :$PORT server:app
